network_id: testnet  # testnet/mainnet
# Send a ping to all peers after ping_interval seconds
ping_interval: 120

harvester:
  # The harvester server (if run) will run on this host and port
  host: 127.0.0.1
  port: 8448
  farmer_peer:
    host: 127.0.0.1
    port: 8447
  # Location of all the plots, default ./plots
  # plot_root: "/mnt/pos"

farmer:
  # The farmer server (if run) will run on this host and port
  host: 127.0.0.1
  port: 8447
  # The farmer will attempt to connect to this full node and harvester
  full_node_peer:
    host: 127.0.0.1
    port: 8444
  harvester_peer:
    host: 127.0.0.1
    port: 8448
  # To send a share to a pool, a block must be faster than this, in seconds
  pool_share_threshold: 12000
  # To send to the full node, a block must be faster than this, in seconds
  propagate_threshold: 10000

# Don't run this unless you want to run VDF clients on the local machine.
timelord_launcher:
  # The server where the VDF clients will connect to.
  host: 127.0.0.1
  port: 8000
  # Number of VDF client processes to keep alive in the local machine.
  process_count: 2

timelord:
  # The timelord server (if run) will run on this host and port
  host: 127.0.0.1
  port: 8446
  # How much recursion to use for the wesolowski VDF proof. This increases the size
  # of the proofs.
  n_wesolowski: 2
  # Provides a list of VDF clients expected to connect to this timelord.
  # For each client, an IP is provided, together with the estimated iterations per second.
  vdf_clients:
    ip:
      - 127.0.0.1
    ips_estimate:
      - 100000
  full_node_peer:
      host: 127.0.0.1
      port: 8444
  # Maximum number of seconds allowed for a client to reconnect to the server.
  max_connection_time: 60
  # The ip and port where the TCP clients will connect. 
  vdf_server:
    host: 127.0.0.1
    port: 8000

full_node:
  # The full node server (if run) will run on this host and port
  host: 127.0.0.1
  port: 8444
  enable_upnp: True
  # Don't send any more than these number of headers and blocks, in one message
  max_headers_to_send: 25
  max_blocks_to_send: 5
  num_sync_batches: 10

  # If node is more than these blocks behind, will do a sync
  sync_blocks_behind_threshold: 20

  # This SSH key is for the ui SSH server
  ssh_filename: config/ssh_host_key
  # How often to connect to introducer if we need to learn more peers
  introducer_connect_interval: 500
  # Continue trying to connect to more peers until this number of connections
  target_peer_count: 10
  # Only connect to peers who we have heard about in the last recent_peer_threshold seconds
  recent_peer_threshold: 6000

  farmer_peer:
      host: 127.0.0.1
      port: 8447
  timelord_peer:
      host: 127.0.0.1
      port: 8446
  introducer_peer:
      # To run the simulation, set host to 127.0.0.1 and port to 8445
      # host: 127.0.0.1
      # port: 8445
      host: introducer.chia.net  # Chia AWS introducer IPv4/IPv6
      port: 8444

introducer:
  host: 127.0.0.1
  port: 8445
  max_peers_to_send: 20
  # The introducer will only return peers who it has seen in the last
  # recent_peer_threshold seconds
  recent_peer_threshold: 6000
